### ISSUE TITLE
Language support not display correct language

### ISSUE THREAD

**Issue by paulallendotuk** [scdoshi/jquery-ajaxchimp#22] opened 2014-07-15 10:36 UTC
Hi, first of all this plugin works great, thanks for sharing.

I'm unable to get error/success messages to display in different languages.

I've included both scripts before closing body tag.

```
<script src="js/plugins/jquery.ajaxchimp.min.js"></script>
<script src="js/plugins/jquery.ajaxchimp.langs.min.js"></script>
```

I've initialised below the scripts like so:

```
$('#mc-form').ajaxChimp({
        language: 'es',
        callback: mailChimpResponse,
    url: 'mailchimp address'
});

function mailChimpResponse(resp) {
    if (resp.result === 'success') {
        $('.mailchimp-success').html('' + resp.msg).fadeIn(900);
        $('.mailchimp-error').fadeOut(400);
    } else if(resp.result === 'error') {
        $('.mailchimp-error').html('' + resp.msg).fadeIn(900);
    }  
}
```

Any ideas guys?

Thanks in advance.

Paul

**Comment by scdoshi** [comment] 2014-11-25 06:08
Duplicate of  #33.

**Closed as completed by scdoshi** 2014-11-25 06:08 UTC
